// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repository

import (
	"context"
)

type Querier interface {
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	DeleteProfile(ctx context.Context, id string) error
	GetManyProfiles(ctx context.Context, arg GetManyProfilesParams) ([]Profile, error)
	GetProfile(ctx context.Context, id string) (Profile, error)
	GetProfileByUsername(ctx context.Context, username string) (Profile, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UsernameTaken(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
